import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import Terminal from 'react-console-emulator';

const style = {
  color: "rgba(128, 255, 128, 0.8)",
  textShadow: "0 0 1ex rgba(51, 255, 51, 1), 0 0 2px rgba(255, 255, 255, 0.8)",
};

const Home: NextPage = () => {
  const router = useRouter();
  const commands = {
    echo: {
      description: 'Echo a passed string.',
      usage: 'echo <string>',
      fn: (...args: string[]) => args.join(' ')
    },
    resume: {
      description: 'Redirects you to my resume page',
      usage: 'resume',
      fn: (...args: string[]) => router.push(`/resume`)
    },
    social: {
      description: 'List relevant professional social media',
      usage: 'social',
      fn: (...args: string[]) => {
        return (
          <ul>
            <li><a href="https://www.linkedin.com/in/trynn2501/">https://www.linkedin.com/in/trynn2501/</a></li>
            <li><a href="https://github.com/Trynn2501" className="whitespace-pre">https://github.com/Trynn2501</a></li>
          </ul>
        )
      } 
    }
  }

  return (
    <>
      <Head>
        <title>Howdy Partner!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="tv">
        <div className="noise"></div>
        <div className="overlay"></div>
        <div className="terminal px-12" id="terminal">
          <nav className="menu flex flex-col">
            <p className="mr-[50%] mt-12"> Hello, My name is Trynn Zala your friendly neighborhood console cowboy. My life is a sequence of strange events.
              So I have become a bit of an expert solving such strange events that happen through electricity,
              language, and society. More intro stuff blah blah blah blah blah blah
            </p>
            <Link href="/resume"><a className="mt-4 indent-2">Resume</a></Link>
            <Link href="/resume"><a className="mt-4 indent-6">Blog</a></Link>
            <Link href="https://worlddomination.ca/"><a className="mt-4 indent-10">Projects</a></Link>
          </nav>
          <Terminal
            className="terminal"
            commands={commands}
            welcomeMessage={''}
            promptLabel={'me@React:~$'}
            inputStyle={style}
            promptLabelStyle={style}
            messageStyle={style}
          />
        </div>
      </main>
    </>
  );
};

export default Home;
